# Generated by Django 5.1.5 on 2025-02-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('emailAddress', models.EmailField(max_length=255, unique=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('createdBy', models.CharField(default=models.CharField(max_length=255, unique=True), max_length=255)),
                ('createdOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('modifiedBy', models.CharField(default='yet to be modified', max_length=255, null=True)),
                ('modifiedOn', models.DateTimeField(null=True)),
            ],
        ),
    ]
