# Generated by Django 5.1.5 on 2025-02-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('emailAddress', models.EmailField(max_length=255, unique=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
